# server setting
server:
  port: 8080

# jpa setting
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zuzuclub?serverTimezone=UTC&characterEncoding=UTF-8
    username: zuzuclub
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

#   security:
#     oauth2:
#       client:
#         registration:
#           google:
#             clientId: 
#             clientSecret: 